name: CI/CD GitHub Actions
on: workflow_dispatch
jobs:
  gtest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - run: git submodule init
      - run: git submodule update
      - run: sudo apt update -y && sudo apt install -y libgtest-dev libgmock-dev
      #- run: pip install --user cpp-coveralls
      #- run: cmake
      #- run: cmake .
      #- run: make
      #- run: make CTEST_OUTPUT_ON_FAILURE=1  test

